<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7GKAUO0" failures="3" tests="4" name="Test" time="9.884" errors="0" timestamp="2021-08-10T15:30:10 IST">
  <testcase classname="demoProject.login.TC_validUser" name="user1" time="0.01"/>
  <testcase classname="demoProject.login.TC_invaliduser" name="user2" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at demoProject.login.TC_invaliduser.user2(TC_invaliduser.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- user2 -->
  <testcase classname="demoProject.login.TC_invalidpassword" name="user3" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at demoProject.login.TC_invalidpassword.user3(TC_invalidpassword.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- user3 -->
  <testcase classname="demoProject.login.TC_bothinvalid" name="user3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at demoProject.login.TC_bothinvalid.user3(TC_bothinvalid.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- user3 -->
</testsuite> <!-- Test -->
